name: Latest blog post workflow
on:
  schedule:
    - cron: '11 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://geiser.cloud/feed/"
          template: |
            - [$title]($url?ref=github.com)$newline
          disable_html_encoding: true
          item_exec: |
            const map = {
              '&quot;': '"',
              '&#39;': "'",
              '&apos;': "'",
              '&amp;' : '&',
              '&lt;'  : '<',
              '&gt;'  : '>'
            };
            post.title = post.title.replace(
              /&quot;|&#39;|&apos;|&amp;|&lt;|&gt;/g,
              m => map[m]
            );
