name: Latest blog post workflow
on:
  schedule:
    - cron: '11 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: "Update this repo's README with latest blog posts"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://geiser.cloud/feed/"
          template: |
            - [$title]($url?ref=github.com)$newline
          disable_html_encoding: true


